spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_MYSQL_URL}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace